<?php

// init

$hash = $_POST['hash']; 
$meta = json_decode($_POST['meta'], true); 

// $filetype = $_POST['filetype'];

$imgs = $_POST['imgs'];
// $sizes = $_POST['sizes'];
$count = count($imgs);

$meta_text = '<div id="meta_text">';
$meta_text .= '<p>Using the '.$meta["gapanalysis"].' aid layer for the '.$meta["adm"].' level of '.$meta["country"].' and the weighted layer, a gap analysis was run to determine areas where projects were being relatively over or underfunded. The data layers used to generate the weighted layer and their assigned weights are: </p>';
$meta_text .= '<ul>';
foreach ($meta["weights"] as $key => $value) {
	$val = $meta["weight_vals"][$key];
	$meta_text .= '<li>'.$value.' ('.$val.')</li>';
}
$meta_text .= '</ul>';
$meta_text .= '</div>';

$main_text = '<p id="main_text">The plot below shows standardized values of aid and data from the weighted layer for the 5 most underfunded and 5 most overfunded areas. The weighted layer is broken down by each raw data layer used to produce the final weight.</p>';
$funding_text = '<p id="funding_text">Breaking down all areas of '.$meta["country"].' at the '.$meta["adm"].' level based on the level of funding they received illustrates the disparity between underfunded and overfunded areas as well as the severity of over and underfunding at the '.$meta["adm"].' level in '.$meta["country"].'. </p>';
$generic_text = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque posuere eu nunc non malesuada. Curabitur vel lobortis dui. Nullam eleifend ac metus nec dignissim. Integer pellentesque augue eget diam volutpat, vel rhoncus mi finibus. Nullam efficitur eleifend sollicitudin. Nulla tincidunt vestibulum quam, eu ultricies neque suscipit eu. Maecenas congue odio malesuada sapien placerat cursus. </p>';
$end_text = '<p id="end_text">Report generated by <a href="http://labs.aiddata.org/aiddata/DASH/">AidData DASH</a>. To learn more about AidData visit <a href="http://aiddata.org">aiddata.org</a> or contact us at data@aiddata.org</p>';

// build raw string
$raw = '';
$raw .= '<style>
			#header {
				margin-bottom:15px;
				padding-bottom:5px;
				border-bottom:1px solid rgba(0,0,0,0.5);
			}
            #header_logo {
				position: fixed;
				top:0;
				left:0;
	            width:100px;
	            float:left;
	        }

	        .grid_title {
	        	float:left;
	            height:50px;
	            width:100%;
				margin-left: 10px;
	            font-family: DejaVuSans;
	            font-size:30px;
	        }
	        .red {
	        	color:red;
	        }

            #map {
                display:inline-block;
                width:66%;
                float:left;
                margin-bottom:10px;
                border: 1px solid black;
            }
            #meta {
                display: inline-block;
                width:33%;
                // height:200px;
                float: left;
                font-family: DejaVuSans;
            }
            .large-chart {
                 width:50%;
            }
            .medium-chart {
                display: inline-block;
                width:66%;
                float: left;
            }
            #info {
                display: inline-block;
                width:33%;               
                float: left;
            }
            #funding {
	            margin-bottom:10px;
	        }

            table {
                border-collapse:collapse;
                cell-spacing: 0px;
                cell-padding: 0px;
                width:100%;
                font-family: DejaVuSans;
            }
            th {
                text-align: center;
            }
            td,th {
                padding:7.5px;
            }
            .tright {
                text-align: right;
            }
            #meta_text {
            	padding:5px;
        	}
            #meta_text p, #meta_text ul, #meta_text li {
            	text-align:left;
                font-family: DejaVuSans;
            	font-size: 9px;
        	}
            #main_text {
            	text-align:left;
                font-family: DejaVuSans;
            	font-size: 10px;
        	}

        	#funding_text {
        		text-align:left;
                font-family: DejaVuSans;
            	font-size: 10px;
        	}

        	#end_text {
        		padding:0px;
        		text-align:center;
                font-family: DejaVuSans;
            	font-size: 10px;        	
            }
            #footer {
	            border-top: 1px solid rgba(0,0,0,0.5);
	            padding-top:5px;
	            margin-top:5px;
	        }
            #footer_logo {
				position: fixed;
				top:bottom;
				left:right;
	            width:100px;
	            float:right;
	        }
		</style>';



$raw .= '<div id="grid">';
$raw .= '<div id="header">';
$raw .= '<img id="header_logo" src="/var/www/html/aiddata/imgs/Logo_notag_large.jpg">';
$raw .= '<div class="grid_title"><span class="red">DASH</span> Gap Analysis Results</div>';
$raw .= '</div>';

// for ($i=0; $i<$count; $i++){


// 	// process actual image
// 	$img = "/var/www/html/aiddata/data/images/" . $imgs[$i];
	
// 	$new_image = substr($img,0,-4) . ".jpeg";
	
// 	$im = new Imagick(); 
// 	$im->readImage($img);
// 	$im->writeImage($new_image);

// 	$img = $new_image;

// 	// manage image and related content layout
// 	if ( strpos($img, 'map') != false ) {
// 		$raw .= '<div class="grid_container">';
// 		$raw .= '<div id="map"><img src="'.$img.'"/></div>';
// 		$raw .= '<div id="meta">';
// 		$raw .= '<table>';
// 		$raw .= '<thead><tr><th colspan=2>Meta Info</th></tr></thead><tbody>';
// 		$raw .= '<tr><td>Country</td><td class="tright">'.$meta["country"].'</td></tr>';
// 		$raw .= '<tr><td>ADM</td><td class="tright">'.$meta["adm"].'</td></tr>';
// 		$raw .= '<tr><td>Aid Layer</td><td class="tright">'.$meta["gapanalysis"].'</td></tr>';
// 		$raw .= '<tr><td colspan=2 style="text-align:center;">Weighted Layers</td></tr>';
// 		foreach ($meta["weights"] as $key => $value) {
// 			$val = $meta["weight_vals"][$key];
// 			$raw .= '<tr><td colspan=2>'.$value.' ('.$val.')</td></tr>';
// 		}
// 		$raw .= '</tbody></table>';
// 		$raw .= '</div>';
// 		$raw .= '</div>';				

// 	} elseif ( strpos($img, 'funding') != false ) {
// 		$raw .= '<div class="grid_container"><div id="info"></div><div class="medium-chart"><img src="'.$img.'"/></div></div>';				

// 	} else {
// 		$raw .= '<div class="grid_container"><div><img src="'.$img.'"/></div></div>';				
// 	}
// }

for ($i=0; $i<$count; $i++){

	// process actual image
	$imgs[$i] = "/var/www/html/aiddata/data/images/" . $imgs[$i];
	
	$new_image = substr($imgs[$i],0,-4) . ".jpeg";
	
	$im = new Imagick(); 
	$im->readImage($imgs[$i]);
	$im->writeImage($new_image);

	$imgs[$i] = $new_image;
}

// map and meta
$raw .= '<div class="grid_container">';

$raw .= '<div id="map"><img src="'.$imgs[0].'"/></div>';

$raw .= '<div id="meta">';
$raw .= $meta_text;
// $raw .= '<table>';
// $raw .= '<thead><tr><th colspan=2>Meta Info</th></tr></thead><tbody>';
// $raw .= '<tr><td>Country</td><td class="tright">'.$meta["country"].'</td></tr>';
// $raw .= '<tr><td>ADM</td><td class="tright">'.$meta["adm"].'</td></tr>';
// $raw .= '<tr><td>Aid Layer</td><td class="tright">'.$meta["gapanalysis"].'</td></tr>';
// $raw .= '<tr><td colspan=2 style="text-align:center;">Weighted Layers</td></tr>';
// foreach ($meta["weights"] as $key => $value) {
// 	$val = $meta["weight_vals"][$key];
// 	$raw .= '<tr><td colspan=2>'.$value.' ('.$val.')</td></tr>';
// }
// $raw .= '</tbody></table>';
$raw .= '</div>';

$raw .= '</div>';				

// wide text
$raw .= '<div>'.$main_text.'</div>';

// extremes chart
$raw .= '<div class="grid_container"><div id="extremes"><img src="'.$imgs[1].'"/></div></div>';				

// funding chart and small text
$raw .= '<div class="grid_container">';
$raw .= '<div id="info">'.$funding_text.'</div>';
$raw .= '<div id="funding" class="medium-chart"><img src="'.$imgs[2].'"/></div>';
$raw .= '</div>';				

// ratio chart
$raw .= '<div class="grid_container"><div id="ratio"><img src="'.$imgs[3].'"/></div></div>';				

// end text
$raw .= '<div id="footer">';
$raw .= '<img id="footer_logo" src="/var/www/html/aiddata/imgs/Logo_notag_large.jpg">';
$raw .= '<div>'.$end_text.'</div>';
$raw .= '</div>';



$raw .= '</div>';
		

// convert markdownextra to html
require_once '/var/www/html/aiddata/libs/Michelf/MarkdownExtra.inc.php';
use \Michelf\MarkdownExtra;
$parser = new MarkdownExtra();
$html = $parser->transform($raw);
file_put_contents("/var/www/html/aiddata/data/documentation.html", $html);

// convert html to pdf
include '/var/www/html/aiddata/libs/mpdf/mpdf.php';
$mpdf = new mPDF();
$mpdf->WriteHTML($html);
$mpdf->Output("/var/www/html/aiddata/data/documentation.pdf", "F");

$out = '../data/documentation.pdf';

echo json_encode($out);

?>